#GDTA ERP \u2014 Configuracion de base de datos
#Tue May 12 14:51:35 CST 2026
db.password=gdta66$
db.url=jdbc\:mysql\://localhost\:3306/bdgdta?useSSL\=false&allowPublicKeyRetrieval\=true&serverTimezone\=America/Mexico_City
db.user=root
